name: 'fraud_features'
version: '1.0.0'
config-version: 2

profile: 'fraud_features'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fraud_features:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
      int_user_txn_online_stats:
        +tags: ["cold_start"]
      int_device_txn_online_stats:
        +tags: ["cold_start"]
      int_user_login_online_stats:
        +tags: ["cold_start"]
    features:
      +materialized: table
      fct_training_dataset:
        +tags: ["archived"]
