name: 'fraud_features'
version: '1.0.0'
config-version: 2

profile: 'fraud_features'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fraud_features:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    features:
      +materialized: table
